Implemented Safe Enum Migration
TUM-Dev/Campus-Backend pull request #128
Opened 2023-01-23 10:19 UTC by Antonwy

2023-01-23 12:19 UTC, COM8 requested changes
Thanks for looking into this!

Looks really promising.

* In golang tests can access functions that are not exported. So I don't see a reason, why for example `BuildEnum` should be upper case.
* Right now you just added the functionality, but you did not migrate the code to use this feature. Is this intended?

2023-01-23 12:19 UTC, COM8 commented on server/backend/migration/safeEnumMigrate.go
> +		return errors.New("could not parse table")
```suggestion
		return errors.New("could not parse enum table")
```

2023-01-23 12:19 UTC, COM8 commented on server/backend/migration/safeEnumMigrate.go
> +		return errors.New("could not alter table")
```suggestion
		return errors.New("could not alter enum table")
```

2023-02-12 21:52 UTC, joschahenningsen approved these changes
Exported methods could use some comments, looks good otherwise :+1:

2023-02-12 21:53 UTC, merged