F: Implemented Base Grade Notification Hook Service
TUM-Dev/Campus-Backend pull request #181
Opened 2023-06-18 19:54 UTC by Antonwy

2023-07-25 17:13 UTC, philippzagar commented
@joschahenningsen Small ping ;)

2023-08-22 07:46 UTC, philippzagar commented
@joschahenningsen Small ping v2 ;)

2023-08-30 13:11 UTC, CommanderStorm requested changes
Overall, I have not found anything controversial.

What I find interesting is that you use a lot more patterns (especially service+repository) than the rest of the project.
Do you think that would be a concept that we could discuss on the next team meeting  (as I think this could be generally usefull to learn about)

2023-08-30 13:11 UTC, CommanderStorm commented on server/model/newExamResultsSubscriber.go
> +	CallbackUrl    string         `json:"callbackUrl"`
In your next PR this changes the primary key to `CallbackUrl`. Do you think we should do this off the start?

2023-09-17 16:24 UTC, Antonwy commented on server/backend/campus_api/campusApi.go
> +	requestUrl := "https://exams.free.beeceptor.com/"
nope. thanks!

2023-09-17 16:36 UTC, Antonwy commented on server/backend/new_exam_results_hook/new_exam_results_scheduling/newExamResultsSchedulingService.go
> +	MockAPIToken    = "DDF9A212B2F80A01C6D0307B8455EEAA"
yes we should set it in an env var. Right now its my api token that I can just deactivate. I think the idea was that we create an account independant token...

2023-09-19 18:13 UTC, CommanderStorm commented on server/model/examResultPublished.go
> +}
renaming to `PublishedExamResult` we can remove this line

2023-09-19 18:13 UTC, CommanderStorm commented on server/backend/migration/20230530000000.go
> +				&model.NewExamResultsSubscriber{},
if the current version of this migration is merged, this `AutoMigrate` is not stable in its outcome. (i.e. future changes to this model would change this migration)
Please only `AutoMigrate`, if you include the migrated model in this file.

2023-09-19 18:13 UTC, CommanderStorm commented on server/backend/migration/20230530000000.go
> +				Type:     null.String{NullString: sql.NullString{String: cron.NewExamResultsHook, Valid: true}},
```suggestion
				Type:     null.StringFrom(cron.NewExamResultsHook),
```

2023-09-19 18:13 UTC, CommanderStorm commented on server/model/newExamResultsSubscriber.go
> +	ApiKey         sql.NullString `json:"-"`
We switched to only using `null` instead of mixing the two in recent PRs

```suggestion
	ApiKey         null.String `json:"-"`
```

2023-09-19 18:13 UTC, CommanderStorm commented on server/model/newExamResultsSubscriber.go
> +	LastNotifiedAt sql.NullTime   `json:"lastNotifiedAt"`
We switched to only using `null` instead of mixing the two.

```suggestion
	LastNotifiedAt null.Time   `json:"lastNotifiedAt"`
```

2023-09-19 18:13 UTC, CommanderStorm commented on server/model/crontab.go
> +	Type     null.String `gorm:"column:type;type:enum ('news', 'mensa', 'chat', 'kino', 'roomfinder', 'ticketsale', 'alarm', 'fileDownload','dishNameDownload','averageRatingComputation', 'iosNotificatio
This is rebasing

```suggestion
	Type     null.String `gorm:"column:type;type:enum ('news', 'mensa', 'kino', 'roomfinder', 'alarm', 'fileDownload','dishNameDownload','averageRatingComputation', 'iosNotifications', 'iosActivityReset', 'canteenHeadCount', 'newExamResultsHook');" json:"type"`
```

2023-09-19 18:13 UTC, CommanderStorm commented on server/backend/new_exam_results_hook/new_exam_results_subscriber/newExamResultsSubscriberRepository.go
> +		log.WithError(err).Errorf("Error while marshalling newGrades")
```suggestion
		log.WithError(err).Error("Error while marshalling newGrades")
```

2023-09-19 18:13 UTC, CommanderStorm commented on server/backend/new_exam_results_hook/new_exam_results_subscriber/newExamResultsSubscriberRepository.go
> +		log.WithError(err).Errorf("Error while creating request")
```suggestion
		log.WithError(err).Error("Error while creating request")
```

2023-09-19 19:50 UTC, CommanderStorm commented
@Antonwy
I think this PR is mergable.
What do you think?

> I think the idea was that we create an account independant token...
How do I create an account independant Token? Ask Andi?

2023-09-19 19:54 UTC, Antonwy commented
> @Antonwy
> 
> I think this PR is mergable.
> 
> What do you think?
> 
> 
> 
> > I think the idea was that we create an account independant token...
> 
> 
> 
> How do I create an account independant Token? Ask Andi?

Yes exactly would probably check with Andy what's the best next step here or if he can already provide a token!

2023-09-19 22:22 UTC, merged