F: Connect iOS Notifications to Grade Published Hook
TUM-Dev/Campus-Backend pull request #186
Opened 2023-07-02 17:36 UTC by Antonwy

2023-07-25 17:14 UTC, philippzagar commented
@joschahenningsen Small ping ;)

2023-08-30 13:33 UTC, CommanderStorm requested changes
Overall:
- Thank you for splitting these PRs apart. This enabled me to do this on two days instead of having to do all at once. Still: this is an immense PR.
- imo the string-comparison-timing attack is something that needs to be adressed before this is mergable
- I have left a lot of other comments

2023-09-17 16:56 UTC, Antonwy commented on docker-compose.yaml
> +      # mysql --user=root --password=secret_root_password campus_db < /entrypoint/schema.sql
<img width="1004" alt="Screenshot 2023-09-17 at 18 55 25@2x" src="https://github.com/TUM-Dev/Campus-Backend/assets/17065257/8dcb265c-075b-446d-97a5-a9a882e120df">

Somehow does the bitnami image not work on my local machine. Did you encounter something similar?

2023-09-17 17:17 UTC, CommanderStorm commented on docker-compose.yaml
> +      # mysql --user=root --password=secret_root_password campus_db < /entrypoint/schema.sql
No, I did not.
- What is your platform? 
- Does deleting the docker volume and re-running fix this issue?

My assumption is that said directory is owned by `root` on your machine. This won't work, as the container is a non-root container.

2023-10-10 21:13 UTC, CommanderStorm commented
@Antonwy Small ping

2023-10-11 09:54 UTC, Antonwy commented
> @Antonwy Small ping

thanks for the ping :) will check it out today or tomorrow!

2023-10-16 19:31 UTC, Antonwy commented on server/model/newExamResultsSubscriber.go
>  	ApiKey         sql.NullString `json:"-"`
The `ApiKey` will be stored, just not returned in the JSON... Or do you mean sth else?

2023-10-16 19:34 UTC, Antonwy commented on server/model/encryptedGrade.go
> +		return err
fair ^^

2023-10-16 20:01 UTC, Antonwy commented on server/api/CampusService.proto
> +message NewExamPublished {
We currently only use examId. However, in the future, another subscriber of this hook may require additional information.

2023-10-16 20:32 UTC, Antonwy commented on server/backend/http_header_authorization/api_key.go
> +		if authorizationKey == envApiKey {
Really not that experienced here to make a decision... But if I understand you correctly we would always have to parse the uuid from the headers ?! Or not?

2023-10-24 12:13 UTC, CommanderStorm commented on server/model/newExamResultsSubscriber.go
>  	ApiKey         sql.NullString `json:"-"`
- please use `null.String` instead of `sql.NullString`
- unsure if storing subscribers without API keys refers to the usage of `sql.NullString`

2024-01-03 00:11 UTC, CommanderStorm commented
@Antonwy ping

2024-01-20 13:12 UTC, CommanderStorm commented
I don't think at this point merging the code is likely due to the ammount of conflicts.

The flutter app will hopefully use firebase notifcations someday
@Antonwy proposed offline that this should be done in a new PR.
I agree with this sentiment. => closing this PR

2024-01-20 13:12 UTC, closed without merging