feat:kino api
TUM-Dev/Campus-Backend pull request #213
Opened 2023-09-04 18:15 UTC by CommanderStorm

This PR implements

I changed the API a bit,
- please make sure if the renamings make sense
- I dropped the trailer field (was 100% null)

TODO:
- [ ] check up on tu-film if we can get a better-scrapable api
- [ ] write a testcase

2023-09-18 20:46 UTC, kordianbruck requested changes

2023-09-18 20:46 UTC, kordianbruck commented on server/api/tumdev/campus_backend.proto
> +  repeated MovieMsgElement movies = 1;
I think we can simplify the data type name here of the message.
```suggestion
  repeated Movie movies = 1;
```

2023-09-18 20:46 UTC, kordianbruck commented on server/api/tumdev/campus_backend.proto
>    string year = 7;
```suggestion
  string release_year = 7;
```

2023-09-18 20:46 UTC, kordianbruck commented on server/api/tumdev/campus_backend.proto
> +  string imdbRating = 12;
```suggestion
  string imdb_rating = 12;
```

Generally try to use snake case in proto. The code gen then correctly translate that to the respective language standard.

> Use PascalCase (with an initial capital) for message names – for example, SongServerRequest. Use lower_snake_case for field names (including oneof field and extension names) – for example, song_name.

https://protobuf.dev/programming-guides/style/#message-field-names

2023-09-18 20:46 UTC, kordianbruck commented on server/api/tumdev/campus_backend.proto
> +  int32 coverID = 14;
```suggestion
  int32 cover_id = 14;
```

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/cron/movies.go
> +	//Get the news feed we want to get our data from
```suggestion
	// Get the news feed we want to get our data from, it contains all the movies
```

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/cron/movies.go
> +	//Parse the data into a struct
```suggestion
	// Parse the data into a struct
```

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/cron/movies.go
> +				log.WithError(err).WithFields(logFields).Error("Cound lot check if movie already exists")
```suggestion
				log.WithError(err).WithFields(logFields).Error("Couldn't check if movie already exists")
```

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/cron/movies.go
> +			if exists {
This can never be true?

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/cron/movies.go
> +			// populate extra data from imdb
```suggestion
			// populate extra data from omdb
```

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/cron/movies.go
> +				URL:  sql.NullString{String: item.Enclosure.Url, Valid: true},
`null.String`?

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/cron/movies.go
> +				log.WithFields(logFields).Info("created movie")
Unnecessary log?

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/cron/movies.go
> +	Year       string
ReleaseYear?

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/cron/movies.go
> +	url := "https://www.omdbapi.com/?r=json&v=1&i=" + id + "&apikey=" + os.Getenv("OMDB_API_KEY")
nit: fmt.Sprintf would be better here.

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/cron/movies.go
> +func getIMDB(id string) (*imdbResults, error) {
```suggestion
func getOMDB(id string) (*imdbResults, error) {
```

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/cron/movies.go
> +type imdbResults struct {
```suggestion
type omdbResults struct {
```

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/cron/movies.go
> +	imdbID := hrefParts[len(hrefParts)-1]
This is the perfect example for a unit test. If you put it into a separate function to separate it from the get operation, it shouldn't be too hard hopefully.

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/cron/movies.go
> +	//Get the news feed we want to get our data from
Or better yet: just move the URL from the news sources to here. Its not a real news source anyway and its a bit confusing to read "news" inside of the movie processing.

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/migration/2023090410000000.go
> +				ID:       null.Int{NullInt64: sql.NullInt64{Int64: 2, Valid: true}},
Simpify the null creaetion

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/migration/2023090410000000.go
> +			if err := tx.Create(&model.Crontab{
you could just return the err here directly

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/migration/migration.go
> +		m.migrate2023090410000000(),
Seems this name has a few extra numbers?

2023-09-18 20:46 UTC, kordianbruck commented on server/backend/movie.go
> +	if err := s.db.Joins("Files").Find(&movies, "kino > ?", req.LastId).Error; err != nil {
Probably it would be good to propergate the context here: https://gorm.io/docs/context.html

2023-09-18 20:46 UTC, kordianbruck commented on server/model/kino.go
> +	Id          int32          `gorm:"primary_key;AUTO_INCREMENT;column:kino;type:int;not null;"`
Please use int64 here - no need to restrict the id length here: https://gorm.io/docs/conventions.html

2023-09-19 16:38 UTC, CommanderStorm commented on server/backend/cron/movies.go
> +			if exists {
Yes

2023-09-22 01:32 UTC, merged